#!/bin/sh

echo "********************************************************************"
echo "Testing secrets analysis before commit"
echo "********************************************************************"

$ git diff --staged --name-only -z | xargs -0 detect-secrets-hook --baseline .secrets-baseline

status=$?

exit $status
