version: 0.2
env:
  shell: bash
  git-credential-helper: yes
  variables:
    REGION: "ap-northeast-2"
    IMAGE_TAG_KEY: "/book/sample/main/tag"
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - apt-get update
      - apt-get install -y jq
  pre_build:
    commands:
      - echo "Print awscli version"
      - aws --version
      - export MY_ECR="${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/${ECR_REPO}"
      - echo "### SRC_VERISON-> ${CODEBUILD_RESOLVED_SOURCE_VERSION} | Logginging to ECR"
      - docker login --username AWS -p $(aws ecr get-login-password --region ${REGION}) ${MY_ECR}
      - export TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - export TAG=$(echo $TAG | sed -e "s/\.//g"| tr '[:upper:]' '[:lower:]')
      - export TAG=$(echo "${TAG:0:8}")
      - export IMAGE_TAG="${TAG}"
      - export REPOSITORY_URI="${MY_ECR}"
      - echo "## TAG-> ${TAG}"
      - |
        echo "### Start App build ###"
        chmod +x ./gradlew 
        ./gradlew clean build  -x test --no-daemon
  build:
    commands:
      - |
        echo "### Building Container Image ###"
        echo $CODEBUILD_SRC_DIR
        echo Build started on `date`
        echo Building the Docker image...
        docker build -t $REPOSITORY_URI:latest ./
        docker images
        docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

      - |
        echo "### Pushing Container Image ###"
        docker push $REPOSITORY_URI:$IMAGE_TAG
      # - cat ./build_scripts/imageDef.json | envsubst > $CODEBUILD_SRC_DIR/imagedefinitions.json
      # - cat $CODEBUILD_SRC_DIR/imagedefinitions.json
  post_build:
    commands:
      - |
        echo "### Pushing Container Image Tag to SSM###"
        aws ssm put-parameter --name $IMAGE_TAG_KEY --value $IMAGE_TAG --overwrite
      - echo "${IMAGE_TAG}" >> build_output.txt
artifacts:
  files:
    - build_output.txt
cache:
  paths:
    - '/root/.gradle/caches/**/*'